import type { RouteRecord } from "./storage";
export type Coordinate = readonly [longitude: number, latitude: number];
export const EXPORT_ATTRIBUTION =
  "Route generated by Trail Mapper. Map data © OpenStreetMap contributors (https://www.openstreetmap.org/copyright).";
export interface PrivateShare {
  title: string;
  text: string;
  url: string;
}
/** Sharing never embeds the route, endpoint labels, coordinates, or browser query/history. */
export function privateRouteShare(
  pageUrl: string,
  distanceMeters?: number,
): PrivateShare {
  const source = new URL(pageUrl);
  if (source.protocol !== "https:" && source.protocol !== "http:")
    throw new Error("Sharing requires a web URL.");
  const distance =
    typeof distanceMeters === "number" &&
    Number.isFinite(distanceMeters) &&
    distanceMeters > 0
      ? ` A ${(distanceMeters / 1609.344).toFixed(1)} mile ride.`
      : "";
  // The route page may carry private data even in its path. Publish only the application origin.
  return {
    title: "Trail Mapper route",
    text: `Plan a trail ride with Trail Mapper.${distance} Exact start and destination are not shared.`,
    url: source.origin + "/",
  };
}
export interface ExportOptions {
  action: "download";
  includeExactEndpoints?: boolean;
  fullRouteApproved?: boolean;
  privacyRadiusMeters?: number;
  attribution?: string;
  segmentBreaks?: readonly number[];
}
export interface RouteGeoJson {
  type: "FeatureCollection";
  attribution: string;
  privacy: "exact-endpoints-approved" | "endpoints-removed";
  features: Array<{
    type: "Feature";
    properties: { name: string; attribution: string };
    geometry: { type: "LineString"; coordinates: number[][] };
  }>;
}
function distance(a: Coordinate, b: Coordinate): number {
  const radians = Math.PI / 180;
  const lat = (b[1] - a[1]) * radians;
  const lon = (b[0] - a[0]) * radians;
  const h =
    Math.sin(lat / 2) ** 2 +
    Math.cos(a[1] * radians) *
      Math.cos(b[1] * radians) *
      Math.sin(lon / 2) ** 2;
  return 6371000 * 2 * Math.asin(Math.sqrt(Math.min(1, h)));
}
function validCoordinate(point: Coordinate): boolean {
  return (
    point.length === 2 &&
    point.every(Number.isFinite) &&
    Math.abs(point[0]) <= 180 &&
    Math.abs(point[1]) <= 90
  );
}
/** Explicit file export, separate from Share. User labels and draft/search history never enter the artifact. */
export function routeGeoJson(
  _record: RouteRecord,
  coordinates: readonly Coordinate[],
  options: ExportOptions,
): RouteGeoJson {
  if (options.action !== "download")
    throw new Error("GeoJSON requires a separate explicit download action.");
  if (options.includeExactEndpoints && !options.fullRouteApproved)
    throw new Error(
      "Confirm inclusion of exact start and destination before exporting the full route.",
    );
  if (coordinates.length < 2 || !coordinates.every(validCoordinate))
    throw new Error("Route geometry is invalid.");
  const attribution = options.attribution?.trim() || EXPORT_ATTRIBUTION;
  const breaks = new Set(options.segmentBreaks ?? []);
  if (
    [...breaks].some(
      (index) =>
        !Number.isInteger(index) || index <= 0 || index >= coordinates.length,
    )
  )
    throw new Error("Invalid route segment boundaries.");
  let lines: Coordinate[][];
  if (options.includeExactEndpoints) {
    lines = [];
    let current: Coordinate[] = [];
    coordinates.forEach((point, index) => {
      if (breaks.has(index)) {
        if (current.length >= 2) lines.push(current);
        current = [];
      }
      current.push(point);
    });
    if (current.length >= 2) lines.push(current);
  } else {
    const radius = Math.max(
      300,
      Number.isFinite(options.privacyRadiusMeters)
        ? options.privacyRadiusMeters!
        : 300,
    );
    const first = coordinates[0];
    const last = coordinates[coordinates.length - 1];
    const sampled: Array<Coordinate | null> = [first];
    // Densifying stops a long segment from crossing a hidden endpoint area unnoticed.
    for (let index = 1; index < coordinates.length; index++) {
      if (breaks.has(index)) {
        sampled.push(null, coordinates[index]);
        continue;
      }
      const a = coordinates[index - 1];
      const b = coordinates[index];
      const steps = Math.ceil(distance(a, b) / 50);
      if (steps > 20_000)
        throw new Error("Route segment is too long for a local trail export.");
      for (let step = 1; step <= Math.max(1, steps); step++) {
        const amount = step / Math.max(1, steps);
        sampled.push([
          a[0] + (b[0] - a[0]) * amount,
          a[1] + (b[1] - a[1]) * amount,
        ]);
      }
    }
    lines = [];
    let current: Coordinate[] = [];
    for (const point of sampled) {
      if (!point) {
        if (current.length >= 2) lines.push(current);
        current = [];
        continue;
      }
      // Extra half-sample margin keeps connecting segments outside the privacy radius.
      if (
        distance(first, point) > radius + 50 &&
        distance(last, point) > radius + 50
      )
        current.push(point);
      else {
        if (current.length >= 2) lines.push(current);
        current = [];
      }
    }
    if (current.length >= 2) lines.push(current);
    if (!lines.length)
      throw new Error(
        "This route is too short to export while hiding exact endpoints.",
      );
  }
  return {
    type: "FeatureCollection",
    attribution,
    privacy: options.includeExactEndpoints
      ? "exact-endpoints-approved"
      : "endpoints-removed",
    features: lines.map((line) => ({
      type: "Feature",
      properties: { name: "Trail Mapper route", attribution },
      geometry: {
        type: "LineString",
        coordinates: line.map((point) => [point[0], point[1]]),
      },
    })),
  };
}
