import type { RouteRecord } from "./storage";
export type Coordinate = readonly [longitude: number, latitude: number];
export const EXPORT_ATTRIBUTION =
  "Route generated by Trail Mapper. Map data © OpenStreetMap contributors (https://www.openstreetmap.org/copyright).";
export interface PrivateShare {
  title: string;
  text: string;
  url: string;
}
/** Sharing never embeds the route, endpoint labels, coordinates, or browser query/history. */
export function privateRouteShare(
  pageUrl: string,
  distanceMeters?: number,
): PrivateShare {
  const source = new URL(pageUrl);
  if (source.protocol !== "https:" && source.protocol !== "http:")
    throw new Error("Sharing requires a web URL.");
  const distance =
    typeof distanceMeters === "number" &&
    Number.isFinite(distanceMeters) &&
    distanceMeters > 0
      ? ` A ${(distanceMeters / 1609.344).toFixed(1)} mile ride.`
      : "";
  // The route page may carry private data even in its path. Publish only the application origin.
  return {
    title: "Trail Mapper route",
    text: `Plan a trail ride with Trail Mapper.${distance} Exact start and destination are not shared.`,
    url: source.origin + "/",
  };
}
/** What one drawable route segment is, from the route result (never a place name or user label). */
export interface ExportSegmentInfo {
  type: string;
  roles: readonly string[];
}
/** A connection the route needed but the dataset does not verify. Exported as its two ends, never as a line. */
export interface ExportGap {
  id: string;
  distanceMeters: number;
  from: Coordinate;
  to: Coordinate;
}
export interface ExportContext {
  kind: string;
  /** Dataset the route was planned on, e.g. its label and whether it is the synthetic review network. */
  dataset: { label: string; mode: string };
  exportedAt: string;
  warnings: readonly string[];
  /** Active closures the route runs through (public notice text only). */
  closures: ReadonlyArray<{
    title: string;
    message: string;
    sourceUrl?: string;
  }>;
  gaps: readonly ExportGap[];
}
export interface ExportOptions {
  action: "download";
  includeExactEndpoints?: boolean;
  fullRouteApproved?: boolean;
  privacyRadiusMeters?: number;
  attribution?: string;
  segmentBreaks?: readonly number[];
  /** One entry per drawable segment (the segments `segmentBreaks` separates); required with `context`. */
  segments?: readonly ExportSegmentInfo[];
  context?: ExportContext;
}
export const EXPORT_METADATA_NOTE =
  "Route status, warnings and unverified connections are included as properties for context. Many map apps ignore properties; check the route status in Trail Mapper before riding.";
type Properties = Record<string, unknown>;
export interface RouteGeoJson {
  type: "FeatureCollection";
  attribution: string;
  privacy: "exact-endpoints-approved" | "endpoints-removed";
  routeContext?: Properties;
  features: Array<
    | {
        type: "Feature";
        properties: Properties;
        geometry: { type: "LineString"; coordinates: number[][] };
      }
    | {
        type: "Feature";
        properties: Properties;
        geometry: { type: "MultiPoint"; coordinates: number[][] };
      }
  >;
}
function distance(a: Coordinate, b: Coordinate): number {
  const radians = Math.PI / 180;
  const lat = (b[1] - a[1]) * radians;
  const lon = (b[0] - a[0]) * radians;
  const h =
    Math.sin(lat / 2) ** 2 +
    Math.cos(a[1] * radians) *
      Math.cos(b[1] * radians) *
      Math.sin(lon / 2) ** 2;
  return 6371000 * 2 * Math.asin(Math.sqrt(Math.min(1, h)));
}
function validCoordinate(point: Coordinate): boolean {
  return (
    point.length === 2 &&
    point.every(Number.isFinite) &&
    Math.abs(point[0]) <= 180 &&
    Math.abs(point[1]) <= 90
  );
}
/** Explicit file export, separate from Share. User labels and draft/search history never enter the artifact. */
export function routeGeoJson(
  _record: RouteRecord,
  coordinates: readonly Coordinate[],
  options: ExportOptions,
): RouteGeoJson {
  if (options.action !== "download")
    throw new Error("GeoJSON requires a separate explicit download action.");
  if (options.includeExactEndpoints && !options.fullRouteApproved)
    throw new Error(
      "Confirm inclusion of exact start and destination before exporting the full route.",
    );
  if (coordinates.length < 2 || !coordinates.every(validCoordinate))
    throw new Error("Route geometry is invalid.");
  const attribution = options.attribution?.trim() || EXPORT_ATTRIBUTION;
  const breaks = new Set(options.segmentBreaks ?? []);
  if (
    [...breaks].some(
      (index) =>
        !Number.isInteger(index) || index <= 0 || index >= coordinates.length,
    )
  )
    throw new Error("Invalid route segment boundaries.");
  const context = options.context,
    segments = options.segments;
  // Context describes segments one by one: refuse to publish it when it cannot be matched to the geometry.
  if (!!context !== !!segments)
    throw new Error(
      "Route details are unavailable for this export. Reopen the route and try again.",
    );
  if (segments && segments.length !== breaks.size + 1)
    throw new Error(
      "Route details do not match the route geometry, so it cannot be exported honestly. Reopen the route and try again.",
    );
  const sortedBreaks = [...breaks].sort((x, y) => x - y);
  const segmentAt = (index: number) =>
    sortedBreaks.filter((boundary) => boundary <= index).length;
  const segmentProperties = (segment: number): Properties => {
    const info = segments?.[segment];
    if (!info) return {};
    const proposed = info.roles.includes("ProposedTrails");
    return {
      segmentType: info.type.toLowerCase(),
      roles: [...info.roles],
      status: proposed ? "proposed" : "existing",
      // Proposed infrastructure is not built: geometry is shown for planning only.
      verified: !proposed,
    };
  };
  type Line = { points: Coordinate[]; segment: number };
  let lines: Line[];
  const first = coordinates[0],
    last = coordinates[coordinates.length - 1];
  let radius = 0;
  if (options.includeExactEndpoints) {
    lines = [];
    let current: Coordinate[] = [];
    let segment = 0;
    coordinates.forEach((point, index) => {
      if (breaks.has(index)) {
        if (current.length >= 2) lines.push({ points: current, segment });
        current = [];
        segment = segmentAt(index);
      }
      current.push(point);
    });
    if (current.length >= 2) lines.push({ points: current, segment });
  } else {
    radius = Math.max(
      300,
      Number.isFinite(options.privacyRadiusMeters)
        ? options.privacyRadiusMeters!
        : 300,
    );
    const sampled: Array<{ point: Coordinate; segment: number } | null> = [
      { point: first, segment: 0 },
    ];
    // Densifying stops a long segment from crossing a hidden endpoint area unnoticed.
    for (let index = 1; index < coordinates.length; index++) {
      if (breaks.has(index)) {
        sampled.push(null, {
          point: coordinates[index],
          segment: segmentAt(index),
        });
        continue;
      }
      const a = coordinates[index - 1];
      const b = coordinates[index];
      const steps = Math.ceil(distance(a, b) / 50);
      if (steps > 20_000)
        throw new Error("Route segment is too long for a local trail export.");
      for (let step = 1; step <= Math.max(1, steps); step++) {
        const amount = step / Math.max(1, steps);
        sampled.push({
          point: [a[0] + (b[0] - a[0]) * amount, a[1] + (b[1] - a[1]) * amount],
          segment: segmentAt(index),
        });
      }
    }
    lines = [];
    let current: Coordinate[] = [];
    let segment = 0;
    const flush = () => {
      if (current.length >= 2) lines.push({ points: current, segment });
      current = [];
    };
    for (const entry of sampled) {
      if (!entry) {
        flush();
        continue;
      }
      // Extra half-sample margin keeps connecting segments outside the privacy radius.
      if (
        distance(first, entry.point) > radius + 50 &&
        distance(last, entry.point) > radius + 50
      ) {
        if (current.length && segment !== entry.segment) flush();
        segment = entry.segment;
        current.push(entry.point);
      } else flush();
    }
    flush();
    if (!lines.length)
      throw new Error(
        "This route is too short to export while hiding exact endpoints.",
      );
  }
  const features: RouteGeoJson["features"] = lines.map((line) => ({
    type: "Feature",
    properties: {
      name: "Trail Mapper route",
      attribution,
      ...segmentProperties(line.segment),
    },
    geometry: {
      type: "LineString",
      coordinates: line.points.map((point) => [point[0], point[1]]),
    },
  }));
  let routeContext: Properties | undefined;
  if (context) {
    const hidden = (point: Coordinate) =>
      !options.includeExactEndpoints &&
      (distance(first, point) <= radius + 50 ||
        distance(last, point) <= radius + 50);
    let omitted = 0;
    for (const gap of context.gaps) {
      // Only the two ends are exported: the connection between them is unverified, so no line is invented.
      if (hidden(gap.from) || hidden(gap.to)) {
        omitted++;
        continue;
      }
      features.push({
        type: "Feature",
        properties: {
          name: "Unverified connection",
          status: "unverified-connection",
          verified: false,
          distanceMeters: Math.round(gap.distanceMeters * 10) / 10,
          note: "The route needs a connection here that the trail data does not verify. Ends only; no path is drawn.",
        },
        geometry: {
          type: "MultiPoint",
          coordinates: [
            [gap.from[0], gap.from[1]],
            [gap.to[0], gap.to[1]],
          ],
        },
      });
    }
    routeContext = {
      kind: context.kind,
      dataset: context.dataset,
      exportedAt: context.exportedAt,
      proposedTrailsIncluded: segments!.some((info) =>
        info.roles.includes("ProposedTrails"),
      ),
      warnings: [...context.warnings],
      closures: context.closures.map((closure) => ({ ...closure })),
      unverifiedConnections: context.gaps.length,
      unverifiedConnectionsOmittedNearHiddenEndpoints: omitted,
      note: EXPORT_METADATA_NOTE,
    };
  }
  return {
    type: "FeatureCollection",
    attribution,
    privacy: options.includeExactEndpoints
      ? "exact-endpoints-approved"
      : "endpoints-removed",
    ...(routeContext ? { routeContext } : {}),
    features,
  };
}
