"""Build prototype.html: the canvas prototype as one page that opens in any browser.

The canvas boards need the design canvas runtime. This inlines prototype/Main.dc.html's markup
and logic with tools/standalone_runtime.js, and adds a picker for the same boards. Run it after
changing the prototype:

    python docs/design/route-to-ride/tools/build_standalone.py
"""

import html
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
DESIGN = os.path.dirname(HERE)
SOURCE = os.path.join(DESIGN, 'prototype', 'Main.dc.html')
RUNTIME = os.path.join(HERE, 'standalone_runtime.js')
OUTPUT = os.path.join(DESIGN, 'prototype.html')

# The same boards as prototype/canvas.json, as props for Main.
BOARDS = [
    ('returning', 'Returning rider', {'history': 'returning', 'placement': 'plan-and-saved', 'startScreen': 'plan'}),
    ('first-use', 'First use', {'history': 'first-use', 'placement': 'plan-and-saved', 'startScreen': 'plan'}),
    ('option-a-saved', 'Option A: Saved, Recent tab', {'history': 'returning', 'placement': 'plan-and-saved', 'startScreen': 'saved-recent'}),
    ('option-b', 'Option B: Plan without Recent', {'history': 'returning', 'placement': 'saved-only', 'startScreen': 'plan'}),
    ('option-b-saved', 'Option B: Saved, Recent tab', {'history': 'returning', 'placement': 'saved-only', 'startScreen': 'saved-recent'}),
]


def main():
    source = open(SOURCE, encoding='utf-8').read().replace('\r\n', '\n')
    markup = source[source.index('<x-dc>') + len('<x-dc>'):source.index('</x-dc>')]
    markup = re.sub(r'<helmet>.*?</helmet>', '', markup, flags=re.S).strip()
    logic = re.search(r'<script type="text/x-dc"[^>]*>(.*?)</script>', source, re.S).group(1)
    assert '</script' not in logic and '</template' not in markup
    runtime = open(RUNTIME, encoding='utf-8').read()

    options = '\n'.join(
        f'        <option value="{key}">{html.escape(label)}</option>' for key, label, _ in BOARDS
    )
    boards = ',\n'.join(
        f"      '{key}': {{ history: '{props['history']}', placement: '{props['placement']}', startScreen: '{props['startScreen']}' }}"
        for key, _, props in BOARDS
    )

    page = f'''<!doctype html>
<!-- Generated by tools/build_standalone.py from prototype/Main.dc.html. Edit those, then rebuild. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Route-to-ride prototype</title>
<link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:wght@400;700&amp;display=swap" rel="stylesheet">
<style>
  body {{ margin: 0; background: #E4EBE7; color: #18211F; font-family: 'Atkinson Hyperlegible', system-ui, sans-serif; }}
  .chrome {{ display: flex; flex-wrap: wrap; gap: 12px; align-items: center; justify-content: center; padding: 16px; }}
  .chrome h1 {{ margin: 0; font-size: 18px; }}
  .chrome label {{ font-size: 15px; font-weight: 700; }}
  .chrome select, .chrome button {{ min-height: 44px; padding: 0 12px; font: inherit; font-size: 15px; border: 1px solid #7C8B86; border-radius: 10px; background: #FFFFFF; color: #18211F; }}
  .phone {{ width: 390px; height: 844px; margin: 0 auto 24px; border-radius: 28px; overflow: hidden; box-shadow: 0 8px 32px rgba(24, 33, 31, 0.25); }}
</style>
</head>
<body>
<div class="chrome">
  <h1>Trail Mapper route-to-ride prototype</h1>
  <label>Board
    <select id="board">
{options}
    </select>
  </label>
  <button type="button" id="restart">Restart</button>
</div>
<div class="phone" id="phone"></div>
<template id="main-template">
{markup}
</template>
<script>
{runtime}
</script>
<script>
(function () {{
  const DCLogic = window.DCStandalone.DCLogic;
{logic}
  const boards = {{
{boards}
  }};
  const phone = document.getElementById('phone');
  const picker = document.getElementById('board');
  const template = document.getElementById('main-template');
  function start() {{
    window.DCStandalone.mount(phone, template, Component, boards[picker.value]);
  }}
  const fromUrl = new URLSearchParams(location.search).get('board');
  if (fromUrl && boards[fromUrl]) picker.value = fromUrl;
  picker.addEventListener('change', start);
  document.getElementById('restart').addEventListener('click', start);
  start();
}})();
</script>
</body>
</html>
'''
    open(OUTPUT, 'w', encoding='utf-8', newline='\n').write(page)
    print('wrote', os.path.relpath(OUTPUT, DESIGN))


if __name__ == '__main__':
    main()
